apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: frontend.local.meow
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-frontend
                port:
                  number: 80
